CREATE TABLE score_card (
 id SERIAL PRIMARY KEY,
 hole_1 INTEGER,
 hole_2 INTEGER,
 hole_3 INTEGER,
 hole_4 INTEGER,
 hole_5 INTEGER,
 hole_6 INTEGER,
 hole_7 INTEGER,
 hole_8 INTEGER,
 hole_9 INTEGER,
 hole_10 INTEGER,
 hole_11 INTEGER,
 hole_12 INTEGER,
 hole_13 INTEGER,
 hole_14 INTEGER,
 hole_15 INTEGER,
 hole_16 INTEGER,
 hole_17 INTEGER,
 hole_18 INTEGER,
 date DATE,
 player_id INTEGER,
 course_id INTEGER
);